// Generated by CoffeeScript 1.10.0
(function() {
  var autoprefixer, browserSync, concat, debug, del, gulp, jade, notify, path, remember, sourcemaps, stylus, uncss, watch;

  gulp = require('gulp');

  stylus = require('gulp-stylus');

  concat = require('gulp-concat');

  autoprefixer = require('gulp-autoprefixer');

  jade = require('gulp-jade');

  sourcemaps = require('gulp-sourcemaps');

  uncss = require('gulp-uncss');

  watch = require('gulp-watch');

  del = require('del');

  notify = require('gulp-notify');

  remember = require('gulp-remember');

  debug = require('gulp-debug');

  path = require('path');

  browserSync = require('browser-sync').create();

  gulp.task('html', function() {
    return gulp.src('development/temp/**/*.html', { since: gulp.lastRun('html') })
          .pipe(gulp.dest('public/'));
  });

  gulp.task('styles', function() {
    return gulp.src('development/styles/**/*.styl', {
      since: gulp.lastRun('styles')
    }).pipe(sourcemaps.init()).pipe(remember('styles')).pipe(concat('style.styl')).pipe(stylus()).on('error', notify.onError({
      title: "Stylus"
    })).pipe(sourcemaps.write()).pipe(gulp.dest('public/css'));
  });

  gulp.task('serve', function() {
    browserSync.init({
      server: {
        baseDir: 'public',
        index: "index.html"
      }
    });
    browserSync.watch('public/**/*.*').on('change', browserSync.reload);
  });

  gulp.task('js', function() {
    return gulp.src('development/js/**/*.js')
          .pipe(gulp.dest('public/js'))
  });

  gulp.task('build', gulp.parallel('html', 'styles', 'js'));

  gulp.task('watch', function() {
    gulp.watch('development/styles/**/*.styl', gulp.series('styles')).on('unlink', function(filepath) {
      remember.forget('styles', path.resolve(filepath));
    });
    gulp.watch('development/temp/**/*.html', gulp.series('html')).on('unlink', function(filepath) {
      remember.forget('html', path.resolve(filepath));
    });
    gulp.watch('development/js/**/*.js', gulp.series('js'));
  });

  gulp.task('default', gulp.series('build', gulp.parallel('serve', 'watch')));

}).call(this);
