// Generated by CoffeeScript 1.10.0
(function() {
  var autoprefixer, concat, del, gulp, jade, sourcemaps, stylus, uncss, watch, webserver;

  gulp = require('gulp');

  stylus = require('gulp-stylus');

  concat = require('gulp-concat');

  autoprefixer = require('gulp-autoprefixer');

  jade = require('gulp-jade');

  sourcemaps = require('gulp-sourcemaps');

  uncss = require('gulp-uncss');

  webserver = require('gulp-webserver');

  watch = require('gulp-watch');

  del = require('del');

  gulp.task('jade', function() {
    return gulp.src('./public/temp/**/*.jade').pipe(jade()).pipe(gulp.dest('./develop'));
  });

  gulp.task('stylus', function() {
    return gulp.src('./public/styles/**/*.styl').pipe(concat('style.styl')).pipe(sourcemaps.init()).pipe(stylus()).pipe(sourcemaps.write()).pipe(uncss({
      html: ['./develop/index.html']
    })).pipe(autoprefixer({
      browsers: ['last 5 versions']
    })).pipe(gulp.dest('./develop/css'));
  });

  gulp.task('watch', function() {
    gulp.watch('./public/styles/**/*.styl', ['stylus']);
    gulp.watch('./public/temp/**/*.jade', ['jade']);
  });

  gulp.task('webserver', function() {
    return gulp.src('./').pipe(webserver({
      livereload: true,
      directoryListing: true,
      open: true
    }));
  });

  gulp.task('default', ['webserver', 'watch']);

}).call(this);
